import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}> <header className="header">
      <span>Next.js Blog</span>
        <a className="link" href="/">Home</a>
        <a className="link" href="/about">About</a>
        <a className="link" href="/contact">Contact</a>
    </header>{children}<footer className="footer">
      <p className="footer-title">© 2023 Blog Name</p>
    </footer></body>
    </html>
  )
}
